<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<div class="r-blog">
                <h1 class="blog-title">Chính Sách Thanh Toán</h1>

                    

<p dir="ltr" style="line-height: 1.7999999999999998; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CHÍNH SÁCH THANH TOÁN CỦA PLAYFUL WONDERS TOYS</span><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><strong><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #000000; background-color: transparent; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Lala Shop cung cấp 3 phương thức thanh toán như sau:</span></strong><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span id="docs-internal-guid-081bd200-7fff-f26a-ec9c-62a11d8dac64"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-weight: bold; font-style: italic; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">1.Đến mua hàng trực tiếp tại cửa hàng:</span></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Thanh toán trực tiếp cho shop</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span id="docs-internal-guid-d4709e64-7fff-0002-e6de-b6a0fd9833f0"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-weight: bold; font-style: italic; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">2. Nhận hàng và thanh toán (COD) trên toàn quốc</span><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">:</span></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Khách hàng có thể đặt hàng và cung cấp đầy đủ thông tin cho shop. sau khi xác nhận đơn hàng shop sẽ chuyển hàng đến tận nơi của khách hàng. Khách hàng sẽ thanh toán trực tiếp cho nhân viên giao hàng, ký xác nhận đã thanh toán.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span id="docs-internal-guid-a417d585-7fff-5df7-7a8e-ed27b2ab8af8"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-weight: bold; font-style: italic; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">3. Thanh toán online:</span></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Khách hàng buộc phải thanh toán trước bằng cách thanh toán online trên web. Trước khi thực hiện chuyển khoản, vui lòng liên hệ nhân viên, để đảm bảo giao dịch chuyển khoản chính xác nhất. khi nhận được tiền. shop sẽ chuyển hàng.</span></p>


                </div>
                 