<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<div class="r-blog">
                <h1 class="blog-title">Chính Sách Thanh Toán</h1>
                <p class="blog-date">
                    <span class="date">11:04 30/11/2023</span>
                    <span>&nbsp;</span>
                    <span class="fb-like fb_iframe_widget" data-href="https://lala.com.vn/chinh-sach-thanh-toan" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=&amp;container_width=0&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-thanh-toan&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=small"><span style="vertical-align: bottom; width: 450px; height: 28px;"><iframe name="f13697d8cb0acf" width="1000px" height="1000px" data-testid="fb:like Facebook Social Plugin" title="fb:like Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v2.12/plugins/like.php?action=like&amp;app_id=&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Dfc71ca67f1957c%26domain%3Dlala.com.vn%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Flala.com.vn%252Ff3938ed9a5c2de4%26relation%3Dparent.parent&amp;container_width=0&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-thanh-toan&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=small" style="border: none; visibility: visible; width: 450px; height: 28px;" class=""></iframe></span></span>
                </p>
                <div class="related-blog">
                    <ul>
                        
                        <li>
                            <a href="/top-tranh-treo-tuong-ban-chay-nhat-thang-32019-1971.html">Top tranh treo tường bán chạy nhất tháng 3/2019</a>
                        </li>
                        
                        <li>
                            <a href="/tranh-treo-cau-thang-an-tuong-cho-moi-khong-gian-noi-that-hien-dai-1941.html">Tranh treo cầu thang ấn tượng cho mọi không gian nội thất hiện đại</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="blog-content" style="">
                    




<p dir="ltr" style="line-height: 1.7999999999999998; text-align: center; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CHÍNH SÁCH THANH TOÁN CỦA LALA</span><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><strong><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #000000; background-color: transparent; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Lala Shop cung cấp 3 phương thức thanh toán như sau:</span></strong><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span id="docs-internal-guid-081bd200-7fff-f26a-ec9c-62a11d8dac64"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-weight: bold; font-style: italic; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">1.Đến mua hàng trực tiếp tại cửa hàng:</span></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Thanh toán trực tiếp cho shop</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span id="docs-internal-guid-d4709e64-7fff-0002-e6de-b6a0fd9833f0"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-weight: bold; font-style: italic; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">2. Nhận hàng và thanh toán (COD) trên toàn quốc</span><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">:</span></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Khách hàng có thể đặt hàng và cung cấp đầy đủ thông tin cho shop. sau khi xác nhận đơn hàng shop sẽ chuyển hàng đến tận nơi của khách hàng. Khách hàng sẽ thanh toán trực tiếp cho nhân viên giao hàng, ký xác nhận đã thanh toán.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span id="docs-internal-guid-a417d585-7fff-5df7-7a8e-ed27b2ab8af8"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-weight: bold; font-style: italic; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">3. Chuyển khoản qua tài khoản ngân hàng:</span></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Trong trường hợp phải gửi xe (cho nhanh) khách hàng buộc phải thanh toán trước bằng cách chuyển tiền vào tài khoản ngân hàng của shop. Trước khi thực hiện chuyển khoản, vui lòng liên hệ nhân viên, để đảm bảo giao dịch chuyển khoản chính xác nhất. Sau khi chuyển, gọi điện thông báo cho shop qua 028.888.11616 - 028.668.73579 - 0907.160.184 để xác nhận đã chuyển tiền. khi nhận được tiền. shop sẽ chuyển hàng.</span></p>


                </div>
                    <div class="fb-like fb_iframe_widget" data-href="https://lala.com.vn/chinh-sach-thanh-toan" data-layout="standard" data-action="like" data-size="large" data-show-faces="true" data-share="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=&amp;container_width=662&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-thanh-toan&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=large"><span style="vertical-align: bottom; width: 450px; height: 28px;"><iframe name="f12ffb5584808ac" width="1000px" height="1000px" data-testid="fb:like Facebook Social Plugin" title="fb:like Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v2.12/plugins/like.php?action=like&amp;app_id=&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df2db2d3e554d70c%26domain%3Dlala.com.vn%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Flala.com.vn%252Ff3938ed9a5c2de4%26relation%3Dparent.parent&amp;container_width=662&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-thanh-toan&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=large" style="border: none; visibility: visible; width: 450px; height: 28px;" class=""></iframe></span></div>
                
            </div>