<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<div class="r-blog">
                <h1 class="blog-title">Chính Sách Giao Hàng</h1>
                <p class="blog-date">
                    <span class="date">12:00 20/12/2018</span>
                    <span>&nbsp;</span>
                    <span class="fb-like fb_iframe_widget" data-href="https://lala.com.vn/chinh-sach-giao-hang-1783.html" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=&amp;container_width=0&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-giao-hang-1783.html&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=small"><span style="vertical-align: bottom; width: 450px; height: 28px;"><iframe name="f27183263617948" width="1000px" height="1000px" data-testid="fb:like Facebook Social Plugin" title="fb:like Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v2.12/plugins/like.php?action=like&amp;app_id=&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df1b224ff00ac708%26domain%3Dlala.com.vn%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Flala.com.vn%252Ff180b17caa4b3f%26relation%3Dparent.parent&amp;container_width=0&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-giao-hang-1783.html&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=small" style="border: none; visibility: visible; width: 450px; height: 28px;" class=""></iframe></span></span>
                </p>
                <div class="related-blog">
                    <ul>
                        
                        <li>
                            <a href="/top-tranh-treo-tuong-ban-chay-nhat-thang-32019-1971.html">Top tranh treo tường bán chạy nhất tháng 3/2019</a>
                        </li>
                        
                        <li>
                            <a href="/tranh-treo-cau-thang-an-tuong-cho-moi-khong-gian-noi-that-hien-dai-1941.html">Tranh treo cầu thang ấn tượng cho mọi không gian nội thất hiện đại</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="blog-content" style="">
                    <div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">Cửa hàng cung cấp các hình thức giao hàng như sau :</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Nhận hàng trực tiếp tại cửa hàng</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Nhân viên giao hàng của cửa hàng giao trực tiếp trong ngày.</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Sử dụng dịch vụ giao hàng của bên thứ 3.</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Hỗ trợ gửi thông qua các hãng vận tải trong nước ( tại các bến xe )</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Gửi hàng thông qua bưu điện</div>
                </div>
                    <div class="fb-like fb_iframe_widget" data-href="https://lala.com.vn/chinh-sach-giao-hang-1783.html" data-layout="standard" data-action="like" data-size="large" data-show-faces="true" data-share="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=&amp;container_width=662&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-giao-hang-1783.html&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=large"><span style="vertical-align: bottom; width: 450px; height: 28px;"><iframe name="fc25f7a2fde0dc" width="1000px" height="1000px" data-testid="fb:like Facebook Social Plugin" title="fb:like Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v2.12/plugins/like.php?action=like&amp;app_id=&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df3a433b0cf2b114%26domain%3Dlala.com.vn%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Flala.com.vn%252Ff180b17caa4b3f%26relation%3Dparent.parent&amp;container_width=662&amp;href=https%3A%2F%2Flala.com.vn%2Fchinh-sach-giao-hang-1783.html&amp;layout=standard&amp;locale=vi_VN&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=large" style="border: none; visibility: visible; width: 450px; height: 28px;" class=""></iframe></span></div>
                
            </div>