<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

    
    <div class="r-blog">
                <h1 class="blog-title">Chính Sách Đổi Trả</h1>

                    

<p dir="ltr" style="line-height: 1.7999999999999998; text-align: center; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Thông tin chi tiết chính sách đổi trả và hoàn tiền tại Shop</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nhằm giúp quý khách an tâm chọn lựa cho mình những sản phẩm ưng ý và phục vụ khách hàng chu đáo, Shop thông báo đến quý khách hàng chính sách đổi trả sản phẩm chi tiết như sau:</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1. Điều kiện áp dụng</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Theo các điều khoản và điều kiện được quy định trong chính sách Trả hàng và Hoàn tiền này và tạo thành một phần của Điều khoản dịch vụ, shop đảm bảo quyền lợi của khách hàng bằng cách cho phép đổi/trả hàng trong thời gian 7 ngày (Kể từ ngày khách hàng nhận được sản phẩm).</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2. Điều kiện trả hàng</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Shop chấp nhận yêu cầu trả hàng và hoàn tiền trong các trường hợp sau:</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">• Người mua đã thanh toán nhưng không nhận được sản phẩm.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">• Sản phẩm bị lỗi hoặc bị hư hại trong quá trình vận chuyển.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">• Người bán giao sai sản phẩm cho Người mua (VD: sai kích cỡ, sai màu sắc, v.vv...).</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3. Các mặt hàng không cho phép đổi trả</span></p>


<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">• Các sản phẩm đặt theo yêu cầu: Sản phẩm in kèm logo, thương hiệu, đặt in theo kích cỡ riêng của khách hàng. Do một số sản phẩm chỉ sản xuất khi khách hàng đặt nên shop không chấp nhận đổi trả chỉ trừ trường hợp sản phẩm lỗi sẽ được đổi sản phẩm mới.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4. Quyền lợi của khách hàng</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Khách hàng cần phải gửi phản hồi theo hướng dẫn của shop trong thời gian quy định là 7 ngày (Kể từ ngày khách hàng nhận được sản phẩm). Sau thời gian đó, nếu Shop không nhận được bất cứ phản hồi nào từ khách hàng, Shop sẽ hiểu rằng khách hàng không có bất cứ khiếu nại gì về sản phẩm.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5. Tình trạng của hàng trả lại</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Để hạn chế các rắc rối phát sinh liên quan đến trả hàng, khách hàng lưu ý cần phải gửi trả sản phẩm bao gồm toàn bộ phụ kiện đi kèm, hóa đơn VAT, tem phiếu bảo hành... nếu có và sản phẩm phải trong tình trạng nguyên vẹn như khi nhận hàng. Shop khuyến khích Người mua chụp lại ảnh sản phẩm ngay khi nhận được để làm bằng chứng đối chiếu/khiếu nại về sau nếu cần.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6. Chi phí trả hàng</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">+ Sản phẩm do lỗi sản xuất: mọi chi phí vận chuyển trả hàng do Shop chi trả.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">+ Lý do khác: mọi chi phí vận chuyển do khách hàng chi trả.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">7. Hoàn tiền cho Hàng trả lại</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Shop sẽ chỉ hoàn tiền cho người mua khi Shop xác nhận đã nhận được hàng trả lại.</span><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br></span><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Lưu ý: Với đơn hàng COD, người mua có trách nhiệm phải cung cấp thông tin tài khoản ngân hàng để nhận tiền hoàn trả.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">8. Liên lạc giữa người bán và người mua</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Shop luôn mong muốn có thể trao đổi với&nbsp; khách hàng bất cứ phát sinh nào trong giao dịch. Do vậy khi gặp vấn đề với đơn hàng hãy liên hệ ngay hotline 000.000.0000 hoặc 000.000.0000 để được hỗ trợ giải quyết trong thời gian sớm nhất.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Mọi thắc mắc về Shop xin vui lòng liên hệ:</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">· Hotline chăm sóc khách hàng: 000.000.0000 - 000.000.0000</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">· Website: <a ></a></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">· Email: hotro@Shop.com.vn</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">· Fanpage:&nbsp; https://www.facebook.com/Shop</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">· Địa chỉ: 1 Võ Văn Ngân, Thủ Đức, Tp. Hồ Chí Minh</span><span id="docs-internal-guid-25f65fd5-7fff-3b11-4327-c06e1f4c7afa"></span></p>


                </div>
                    