<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<div class="r-blog">
                <h1 class="blog-title">Chính Sách Giao Hàng</h1>
               <div class="blog-content" style="">
                    <div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">Cửa hàng cung cấp các hình thức giao hàng như sau :</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Nhận hàng trực tiếp tại cửa hàng</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Nhân viên giao hàng của cửa hàng giao trực tiếp trong ngày.</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Sử dụng dịch vụ giao hàng của bên thứ 3.</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Hỗ trợ gửi thông qua các hãng vận tải trong nước ( tại các bến xe )</div><div style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; margin-top: 0px; margin-right: 0px; margin-left: 0px; border: none; color: rgb(51, 51, 51); background: none !important; margin-bottom: 10px !important; box-shadow: none !important;">- Gửi hàng thông qua bưu điện</div>
                </div>
                  