<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<div class="r-blog">
                <h1 class="blog-title">Chính Sách Bảo Mật Thanh Toán  </h1>

                <div class="blog-content" style="">

<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Cám ơn quý khách đã truy cập vào website Shop.com.vn được vận hành bởi Shop Shop. Chúng tôi tôn trọng và cam kết sẽ bảo mật những thông tin mang tính riêng tư của bạn. Xin vui lòng đọc bản Chính sách bảo mật dưới đây để hiểu hơn những cam kết mà chúng tôi thực hiện nhằm tôn trọng và bảo vệ quyền lợi của người truy cập.</p>
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Chính sách bảo mật sẽ giải thích cách chúng tôi tiếp nhận, sử dụng và (trong trường hợp nào đó) tiết lộ thông tin cá nhân của bạn. Chính sách cũng sẽ giải thích các bước chúng tôi thực hiện để bảo mật thông tin cá nhân của khách hàng. Cuối cùng, Chính sách bảo mật sẽ giải thích quyền lựa chọn của quý khách về việc thu thập, sử dụng và tiết lộ thông tin cá nhân của mình.</p>
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Bảo vệ dữ liệu cá nhân và gây dựng được niềm tin cho quý khách là vấn đề rất quan trọng với chúng tôi. Vì vậy, chúng tôi sẽ dùng tên và các thông tin khác liên quan đến quý khách tuân thủ theo nội dung của Chính sách bảo mật. Chúng tôi chỉ thu thập những thông tin cần thiết liên quan đến giao dịch mua bán.</p>
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Chúng tôi sẽ giữ thông tin của khách hàng trong thời gian luật pháp quy định hoặc cho mục đích nào đó. Quý khách có thể truy cập vào website và trình duyệt mà không cần phải cung cấp chi tiết cá nhân. Lúc đó, bạn đang ẩn danh và chúng tôi không thể biết bạn là ai nếu bạn không đăng nhập vào tài khoản của mình.</p>


<h2 style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-weight: bold; color: rgb(0, 0, 0); margin-top: 20px; margin-bottom: 10px; background: none; margin-left: 0px; text-rendering: optimizeLegibility; line-height: 38px !important; font-size: 30px !important; margin-right: 0px !important; padding: 0px !important;">1. Thu thập thông tin cá nhân</h2> 
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Chúng tôi có thể dùng thông tin cá nhân của bạn để nghiên cứu thị trường. chi tiết sẽ được ẩn và chỉ được dùng để thống kê. Quý khách có thể từ chối không tham gia bất cứ lúc nào. Bất kỳ câu trả lời cho khảo sát hoặc thăm dò dư luận mà chúng tôi cần bạn làm sẽ không được chuyển cho bên thứ ba. Việc cần thiết duy nhất là tiết lộ email của bạn nếu bạn muốn tham gia. Câu trả lời sẽ được lưu tách riêng với email của bạn.</p>
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Bạn sẽ nhận được thông tin về chúng tôi, về website, các website khác, sản phẩm, doanh số bán hàng, bản tin, bất cứ những gì liên quan đến các công ty nằm trong nhóm hoặc các đối tác kinh doanh. Nếu quý khách không muốn nhận những thông tin này, vui lòng nhấn vào link từ chối trong bất kỳ email chúng tôi gửi cho bạn. Trong vòng 7 ngày nhận chỉ dẫn của bạn, chúng tôi sẽ ngừng gửi thông tin. Nếu thấy không rõ, chúng tôi sẽ liên lạc với bạn.</p>
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Chúng tôi sẽ tiếp tục giấu tên dữ liệu người dùng trên website và sử dụng cho nhiều mục đích khác nhau, bao gồm việc xác định vị trí của người dùng và cách sử dụng các khía cạnh nhất định của website hoặc đường link chứa trong email tới người dùng và cung cấp dữ liệu ẩn danh đó cho bên thứ 3 là nhà xuất bản. Tuy nhiên, dữ liệu này không có khả năng xác định cá nhân.</p>

<h2 style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-weight: bold; color: rgb(0, 0, 0); margin-top: 20px; margin-bottom: 10px; background: none; margin-left: 0px; text-rendering: optimizeLegibility; line-height: 38px !important; font-size: 30px !important; margin-right: 0px !important; padding: 0px !important;">2. Bảo mật</h2>
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Chúng tôi khuyên quý khách rằng quý khách không nên đưa thông tin chi tiết về việc thanh toán với bất kỳ ai bằng e-mail, chúng tôi không chịu trách nhiệm về những mất mát quý khách có thể gánh chịu trong việc trao đổi thông tin của quý khách qua internet hoặc email.</p>
 
<h2 style="box-sizing: border-box; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-weight: bold; color: rgb(0, 0, 0); margin-top: 20px; margin-bottom: 10px; background: none; margin-left: 0px; text-rendering: optimizeLegibility; line-height: 38px !important; font-size: 30px !important; margin-right: 0px !important; padding: 0px !important;">3. Quyền lợi khách hàng</h2>
<p style="box-sizing: border-box; margin-top: 5px; margin-right: 0px; margin-left: 0px; font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 24px; border: none; color: rgb(51, 51, 51); margin-bottom: 10px !important; background: none !important; box-shadow: none !important;">Quý khách có quyền yêu cầu truy cập vào dữ liệu cá nhân của mình, có quyền yêu cầu chúng tôi sửa lại những sai sót trong dữ liệu của bạn mà không mất phí. Bất cứ lúc nào bạn cũng có quyền yêu cầu chúng tôi ngưng sử dụng dữ liệu cá nhân của bạn cho mục đích tiếp thị.</p> 
                </div>
                  