<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<div class="r-blog">
                <h1 class="blog-title">Giới thiệu Công ty CTY TNHH PLAYFUL WONDERS TOYS</h1>

                <div class="blog-content" style="">
                    

<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Công ty CTY TNHH PLAYFUL WONDERS TOYS được thành lập vào tháng 11/2023, là một trong những đơn vị sản xuất và phân phối trực tiếp lĩnh vực đồ chơi.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Lala Shop qua nhiều năm phát triển, luôn tự hào là thương hiệu uy tín đã phân phối rộng khắp TpHCM cũng như trên toàn quốc, được nhiều cá nhân, tổ chức doanh nghiệp, công ty và các nhà hàng tin tưởng giao trọng trách thổi sinh khí vào không gian một cách tinh tế nhất.</span></p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman', serif; font-size: 12pt; text-align: justify;"><img src="https://i.pinimg.com/564x/a4/ef/46/a4ef46d84d8f06cc6c8602ba4b7595f7.jpg"></span><span style="font-family: 'Times New Roman', serif; font-size: 12pt; text-align: justify;"></span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><strong><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">Với sứ mệnh:</span></strong></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">Chúng tôi tự hào là đơn vị hàng đầu trong việc cung cấp đồ chơi đa dạng và phong phú, mang lại niềm vui và trải nghiệm giáo dục cho mọi lứa tuổi. Với phương châm "Khám phá, Sáng tạo, và Phát triển", chúng tôi cam kết không chỉ là địa điểm mua sắm mà còn là đối tác đáng tin cậy của gia đình.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">Đội ngũ chúng tôi không ngừng nỗ lực để đưa đến thị trường những sản phẩm đồ chơi chất lượng, an toàn và giáo dục. Chúng tôi tự tin rằng mỗi sản phẩm trong danh mục của chúng tôi không chỉ mang lại niềm vui cho trẻ nhỏ mà còn góp phần vào sự phát triển toàn diện của họ. Hãy đến với chúng tôi, nơi mà niềm vui và sự sáng tạo kết nối mọi gia đình!.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><strong><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">PLAYFUL WONDERS TOYS chuyên cung cấp các dịch vụ và sản phẩm bao gồm:</span></strong></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">PLAYFUL WONDERS TOYS là địa chỉ hàng đầu khi bạn tìm kiếm đồ chơi đa dạng và phong phú cho các bé yêu của mình. Cửa hàng có đa dạng các sản phẩm như gấu bông, gumpla, công chúa,...</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 12pt; margin-bottom: 12pt;"><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">Luôn được cập nhật theo xu hướng mới nhất, với thiết kế độc đáo, giá cả tốt nhất thị trường, nhiều phong cách khác nhau.</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><strong><span style="font-size: 14pt; font-family: 'Times New Roman', serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">Hình ảnh các dòng sản phẩm chủ lực:</span></strong></p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman', serif; font-size: 12pt; text-align: justify;"><img src="https://cf.shopee.vn/file/6ee45bf7ab6f761ad58e92235555ccf6" src=""  img src="https://bizweb.dktcdn.net/100/334/916/products/llhat-4573102591586.jpg?v=1672608361247"alt="Các dòng sản phẩm chủ lực tại Shop" width="960" height="540"></span><span style="font-family: 'Times New Roman', serif; font-size: 12pt; text-align: justify;"></span></p>
<p style="text-align: center;">&nbsp;</p>

<
<h3 style="text-align: justify;">&nbsp;</h3>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><strong><span style="font-size: 14pt; font-family: 'Times New Roman', serif; color: #000000; background-color: transparent; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Thông tin liên hệ:</span></strong></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Mã số thuế: 000000000</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Địa chỉ trụ sở chính: Số 1 VVN, Thủ Đức, Thành phố Hồ Chí Minh, Việt Nam</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Cửa hàng kinh doanh: Số 1 VVN,Thủ Đức, TpHCM</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Mở cửa các ngày thứ 2 - 7 từ 8h - 21h, chủ nhật từ 9h - 18h</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Hotline: 000.000.0000 - 000.000.0000 - 000.000.0000</span></p>
<p dir="ltr" style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 10pt;"><span style="font-size: 13.999999999999998pt; font-family: 'Times New Roman',serif; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- Nhận giao hàng toàn quốc và thanh toán sau khi nhận hàng</span></p>

                </div>
                    

